// <auto-generated />
using System;
using ControleAcces.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAcces.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922072848_AjoutRaisonsLogAcces")]
    partial class AjoutRaisonsLogAcces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAcces.Api.Models.Badge", b =>
                {
                    b.Property<int>("IdBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBadge"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("UidBadge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBadge");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.DroitAcces", b =>
                {
                    b.Property<int>("IdDroit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDroit"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBadge")
                        .HasColumnType("integer");

                    b.Property<int>("IdZone")
                        .HasColumnType("integer");

                    b.HasKey("IdDroit");

                    b.HasIndex("IdBadge");

                    b.HasIndex("IdZone");

                    b.ToTable("DroitsAcces");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Empreinte", b =>
                {
                    b.Property<int>("IdEmpreinte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpreinte"));

                    b.Property<DateTime>("DateEnrolement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TemplatesBiometrique")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("IdEmpreinte");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Empreintes");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.LogAcces", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBadge")
                        .HasColumnType("integer");

                    b.Property<int>("IdZone")
                        .HasColumnType("integer");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Raisons")
                        .HasColumnType("text");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLog");

                    b.HasIndex("IdBadge");

                    b.HasIndex("IdZone");

                    b.ToTable("LogAcces");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnActivite")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Zone", b =>
                {
                    b.Property<int>("IdZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZone"));

                    b.Property<string>("NiveauSecurite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdZone");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Badge", b =>
                {
                    b.HasOne("ControleAcces.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.DroitAcces", b =>
                {
                    b.HasOne("ControleAcces.Api.Models.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("IdBadge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcces.Api.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("IdZone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Empreinte", b =>
                {
                    b.HasOne("ControleAcces.Api.Models.Utilisateur", "Utilisateur")
                        .WithOne("Empreinte")
                        .HasForeignKey("ControleAcces.Api.Models.Empreinte", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.LogAcces", b =>
                {
                    b.HasOne("ControleAcces.Api.Models.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("IdBadge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcces.Api.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("IdZone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ControleAcces.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("Empreinte");
                });
#pragma warning restore 612, 618
        }
    }
}
